version: '3.8'

services:
  acados-db:
    image: mysql:8.0
    container_name: acados-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acados_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - acados-network
      
  acados-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: acados-phpmyadmin
    restart: always
    environment:
      PMA_HOST: acados-db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - acados-db
    networks:
      - acados-network
volumes:
  mysql_data:
    driver: local

networks:
  acados-network:
    driver: bridge