
@startuml
title AcadOS - Student Use Case Diagram
left to right direction
skinparam packageStyle rectangle

actor "Student" as Student

rectangle "AcadOS (Student Scope)" {
    package "Authentication" {
        usecase "Login" as UC_SLogin
        usecase "Logout" as UC_SLogout
    }
    package "Course Browsing & Registration" {
        usecase "View Course" as UC_SViewCourse
        usecase "View Section" as UC_SViewSection
        usecase "View Capacity" as UC_SViewCapacity
        usecase "Register Course" as UC_SRegister
        usecase "Withdraw Course" as UC_SWithdraw
    }
    package "Student Schedule" {
        usecase "View Own Schedule" as UC_SViewOwnSchedule
        usecase "View Registered Section Schedule" as UC_SViewRegSchedule
    }
    package "Academic Calendar & Events" {
        usecase "View Academic Calendar" as UC_SViewCalendar
        usecase "View Public Holiday" as UC_SViewHoliday
    }
    package "Notification" {
        usecase "View Notification" as UC_SViewNotif
        usecase "Read Notification" as UC_SReadNotif
    }
}

Student --> UC_SLogin
Student --> UC_SLogout
Student --> UC_SViewCourse
Student --> UC_SViewSection
Student --> UC_SViewCapacity
Student --> UC_SRegister
Student --> UC_SWithdraw
Student --> UC_SViewOwnSchedule
Student --> UC_SViewRegSchedule
Student --> UC_SViewCalendar
Student --> UC_SViewHoliday
Student --> UC_SViewNotif
Student --> UC_SReadNotif
@enduml